import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Contact.module.scss'

export default function Contact() {
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        ...
      </header>
      <main>
        <aside>
          ...
        </aside>
        <section>
          ...
        </section>
      </main>
      <footer>
          ...
      </footer>
    </div>
  )

}