import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {/* ===================== NAV ===================== */}
        <header classNameName="header">
          <nav classNameName="navbar navbar-expand-lg ">
            <div classNameName="container row">
              <div classNameName="col-sm-2  ">
                <img classNameName="w-50" src="img/manga.jpg" alt="" />
              </div>
              <div classNameName="col-sm-8 d-flex justify-content-center">
                <ul className="nav nav-tabs">
                  <li className="nav-item">
                    <a className="nav-link active" aria-current="page" href="#">
                      Active
                    </a>
                  </li>
                  <li classNameName="nav-item dropdown">
                    <a
                      className="nav-link dropdown-toggle"
                      data-bs-toggle="dropdown"
                      href="#"
                      role="button"
                      aria-expanded="false"
                    >
                      Dropdown
                    </a>
                    <ul className="dropdown-menu">
                      <li>
                        <a className="dropdown-item" href="#">
                          Action
                        </a>
                      </li>
                      <li>
                        <a className="dropdown-item" href="#">
                          Another action
                        </a>
                      </li>
                      <li>
                        <a className="dropdown-item" href="#">
                          Something else here
                        </a>
                      </li>
                    </ul>
                  </li>
                  <li className="nav-item">
                    <a className="nav-link" href="#">
                      Link
                    </a>
                  </li>
                  <li className="nav-item">
                    <a className="nav-link disabled">Disabled</a>
                  </li>
                </ul>
              </div>
              <div classNameName="input-group col-sm-2">
                <div classNameName="input-group-prepend">
                  <svg
                    xmlns=""
                    width="16"
                    height="16"
                    fill="currentColor"
                    classNameName="bi bi-search text-secondary"
                    viewBox="0 0 16 16"
                  >
                    <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
                  </svg>
                  <input classNameName="" type="text" />
                </div>
              </div>
            </div>
          </nav>
        </header>
      </div>
      {/* ===================== HOME ===================== */}
      <main classNameName="l-main">
        <section classNameName="home bd-grid" id="home">
          <div classNameName="home__data">
            <h2 classNameName="home__title">Bienvenue dans l'univers de</h2>
            <h1 classNameName="home__title">Webtoon</h1>
            <a href="#" classNameName="button">
              Qui sommes nous?
            </a>
          </div>
          <div classNameName="home__img">
            <img src="/web/public/Adult-Arthur.webp" alt="webtoon Arthur"></img>
          </div>
        </section>
        {/* ===================== ANIME ===================== */}
        <section classNameName="pt-2">
          <div classNameName="container">
            <h2 classNameName="text-secondary " id="titre">
              webtoon
            </h2>
          </div>
          <div classNameName="row g-4 ">
            <div classNameName="col-md-6 col-lg-3">
              <div classNameName="card ">
                <div classNameName="card-body text-center">
                  <img
                    src="../assets/the return.jpg"
                    alt=""
                    classNameName="anime"
                  />
                  <h3 classNameName="text-secondary">
                    the return of the disaster className hero
                  </h3>
                  <p classNameName="text-secondary">
                    Il était une fois un héros qui considéré autre fois comme le
                    plus puissant de la Terre. « Mais il est mort… Comment une
                    personne désignée comme morte pourrait-il revenir ? » «
                    Ouais, j’aimerais bien voir ça, moi aussi. » Mais 20 années
                    plus tard, il revint. « Pourquoi êtes-vous aussi choqués,
                    les gars ? À vois vos gueules, on pourrait croire que vous
                    vous sentez coupable ? » ‘Ces enfoirés… je vais pas les
                    laisser s’en tirer comme ça…
                  </p>
                  <a
                    classNameName="btn bnt-info"
                    href="https://mangas-origines.fr/catalogue/the-return-of-the-disaster-className-hero/"
                    id="on"
                  >
                    Lire le Webtoon
                  </a>
                </div>
              </div>
            </div>
            <div classNameName="col-md-6 col-lg-3">
              <div classNameName="card">
                <div classNameName="card-body text-center">
                  <img
                    src="../assets/unordinary.jpg"
                    alt=""
                    classNameName="anime"
                  />
                  <h3 classNameName="text-info">unordinary</h3>
                  <p classNameName="text-info">
                    {" "}
                    Le monde n'est pas parfait. Apprendre à gérer ses
                    imperfections fait partie de la vie. Mais il arrive un
                    moment où ces défauts forcent une révélation... que quelque
                    chose doit changer...
                  </p>
                  <a
                    classNameName="btn bnt-info text-info"
                    href="https://www.webtoons.com/fr/fantasy/unordinary/list?title_no=1847"
                    id="one"
                  >
                    Lire le Webtoon
                  </a>
                </div>
              </div>
            </div>
            <div classNameName="col-md-6 col-lg-3">
              <div classNameName="card ">
                <div classNameName="card-body text-center">
                  <img
                    src="../assets/solo leveling.jpg"
                    alt=""
                    classNameName="anime"
                  />
                  <h3 classNameName="text-warning">solo leveling</h3>
                  <p classNameName="text-warning">
                    Dix ans auparavant, des portails ont commencé à apparaître
                    un peu partout dans le monde, Ces portails peuvent connecter
                    notre monde à un monde peuplé de monstres et de créatures.
                    Des personnes ordinaires ont acquis la capacité de chasser
                    ces derniers. Sur les appelle les chasseurs. Sung Jin-Woo
                    est le plus faible des chasseurs de rang E, autrement dit,
                    le plus faible parmi les faibles. Il est donc surnommé par
                    ses confrères chasseurs « le faible ». En tout cas il
                    l'était, jusqu'à ce qu'il se retrouve piégé dans un donjon
                    et y acquière une capacité… étrange. Il peut désormais voir
                    une interface de recherche. Sung Jin Woo va-t-il réussir à
                    devenir le plus puissant des chasseurs tout en surmontant
                    les épreuves et les conspirations ?
                  </p>
                  <a
                    classNameName="btn bnt-info text-warning"
                    href="https://www.sololeveling.fr/"
                    id="na"
                  >
                    Lire le Webtoon
                  </a>
                </div>
              </div>
            </div>
            <div classNameName="col-md-6 col-lg-3">
              <div classNameName="card">
                <div classNameName="card-body text-center">
                  <img
                    src="../assets/arthur.jpg"
                    alt=""
                    classNameName="anime"
                  />
                  <h3 classNameName="text-danger">
                    The Beginning After The End
                  </h3>
                  <p classNameName="text-danger">
                    Le roi Grey possède une force, une richesse et un prestige
                    inégalés dans un monde régi par les capacités martiales.
                    Cependant, la solitude suit de près les détenteurs de grands
                    pouvoirs. Sous l'apparence glamour d'un roi puissant se
                    cache la coquille de l'homme, dépourvue de but et de
                    volonté. Réincarné dans un nouveau monde rempli de magie et
                    de monstres, le roi a une seconde chance de revivre sa vie.
                    Corriger les erreurs de son passé ne sera cependant pas son
                    seul défi. Sous la paix et la prospérité du nouveau monde se
                    cache un courant sous-jacent qui menace de détruire tout ce
                    pour quoi il a travaillé, remettant en question son rôle et
                    la raison pour laquelle il est né de nouveau.
                  </p>
                  <a
                    classNameName="btn bnt-info text-danger"
                    href="https://www.thebeginningaftertheend.fr/"
                    id="dr"
                  >
                    Lire le Webtoon
                  </a>
                </div>
              </div>
            </div>
          </div>
        </section>
        {/* ===================== CONTACT ===================== */}
        <section classNameName="contact section" id="contact">
          <h2 classNameName="section-title">Contact</h2>
          <div classNameName="contact__container bd-grid">
            <form action="" classNameName="contact__form">
              <input
                type="text"
                placeholder="Name"
                classNameName="contact__input"
              ></input>
              <input
                type="mail"
                placeholder="Email"
                classNameName="contact__input"
              ></input>
              <textarea
                name=""
                id=""
                cols="0"
                rows="10"
                classNameName="contact__input"
              ></textarea>
              <button
                classNameName="btn btn-primary"
                type="submit"
                value="Envoyer"
              ></button>
            </form>
          </div>
        </section>
      </main>
      {/* ===================== Footer ===================== */}
      <footer classNameName="footer">
        <p classNameName="footer__title">Pc pour tous</p>
        <div>
          <a href="#" classNameName="footer__icon">
            <i classNameName="bx bxl-facebook"></i>
          </a>
          <a href="#" classNameName="footer__icon">
            <i classNameName="bx bxl-instagram"></i>
          </a>
          <a href="#" classNameName="footer__icon">
            <i classNameName="bx bxl-twitter"></i>
          </a>
        </div>
        <p classNameName="footer__copy">&#169; Team6. All rigths reserved</p>
      </footer>

      <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"
      ></script>
      <script
        src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
        integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
        crossorigin="anonymous"
      ></script>
      <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
        crossorigin="anonymous"
      ></script>
      <script src="jquery-3.6.0.js"></script>
    </div>
  );

}
